version: '3'

volumes:
  db-data:

services:
  be_184344_mysql:
    image: ghcr.io/pr0tex/mysql:latest
    build:
      context: .
      dockerfile: dockerfiles/database.Dockerfile
    ports:
      - "8306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-u${DB_USER}", "-p${DB_PASSWD}" ]
      interval: 10s
      retries: 10

  be_184344_prestashop:
    image: ghcr.io/pr0tex/prestashop:latest
    build:
      dockerfile: dockerfiles/presta.Dockerfile  
      context: .
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
      PS_LANGUAGE: ${PS_LANGUAGE}
      PS_COUNTRY: ${PS_COUNTRY}
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO}
      PS_ERASE_DB: ${PS_ERASE_DB}
      PS_DEMO_MODE: ${PS_DEMO_MODE}
      PS_INSTALL_DB: ${PS_INSTALL_DB}
      PS_DOMAIN: ${PS_DOMAIN}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_ENABLE_SSL: ${PS_ENABLE_SSL}
      SHOP_HTTP_PORT: 80
      SHOP_HTTPS_PORT: 443
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./app:/var/www/html
    depends_on:
      be_184344_mysql:
        condition: service_healthy
