version: '3'

volumes:
  be_184344_db_data:
  be_184344_prestashop_data:

services:
  be_184344_mysql:
    image: ghcr.io/pr0tex/be_184344_mysql:latest
    volumes:
      - be_184344_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-u${DB_USER}", "-p${DB_PASSWD}" ]
      interval: 10s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  be_184344_prestashop:
    image: ghcr.io/pr0tex/be_184344_prestashop:latest
    environment:
      DB_SERVER: be_184344_mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: prestashop
      PS_LANGUAGE: pl
      PS_COUNTRY: pl
      PS_INSTALL_AUTO: 1
      PS_ERASE_DB: 1
      PS_DEMO_MODE: 0
      PS_INSTALL_DB: 1
      PS_DOMAIN: localhost:18434
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_ENABLE_SSL: 1
      SHOP_HTTP_PORT: 18433
      SHOP_HTTPS_PORT: 18434
    ports:
      - "18433:80"
      - "18434:443"
    volumes:
       - be_184344_prestashop_data:/var/www/html
    depends_on:
      be_184344_mysql:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
