version: '3'

volumes:
  db-data:

services:
  mysql:
    image: ghcr.io/pr0tex/mysql:latest
    build:
      context: .
      dockerfile: dockerfiles/database.Dockerfile
    ports:
      - "8306:3306"
    volumes:
      - db-data:/var/lib/mysql
      # - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    restart: always
  prestashop-git:
    image: ghcr.io/pr0tex/prestashop:latest
    build:
      dockerfile: dockerfiles/presta.Dockerfile  
      context: .
    environment:
      # DISABLE_MAKE: ${DISABLE_MAKE:-0} #Disable makefile
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}
      PS_ERASE_DB: ${PS_ERASE_DB}
      PS_DEMO_MODE: ${PS_DEMO_MODE}
      PS_INSTALL_DB: ${PS_INSTALL_DB}
      DB_PASSWD: ${DB_PASSWD:-prestashop}
      DB_NAME: ${DB_NAME:-prestashop}
      DB_SERVER: ${DB_SERVER:-mysql}
      PS_DOMAIN: ${PS_DOMAIN}
      # PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_ENABLE_SSL: ${PS_ENABLE_SSL}
    ports:
      - 80:80
      - 443:443
    volumes:
       - ./app:/var/www/html
    # depends_on:
    #   mysql:
    #     condition: service_healthy
